package StoredClasses;

import StoredClasses.annotations.AutoGenerated;
import StoredClasses.annotations.NotNull;
import StoredClasses.enums.*;
import StoredClasses.forms.HumanBeingForm;

import java.time.LocalDateTime;

public class HumanBeing implements Comparable<HumanBeing> {
    public static long idCounter = 1;
    public HumanBeing(HumanBeingForm h){
        this.name = h.getName();
        this.mood = h.getMood();
        this.weaponType = h.getWeaponType();
        this.impactSpeed = h.getImpactSpeed();
        this.hasToothpick = h.getHasToothPick();
        this.realHero = h.getRealHero();
        this.coordinates = h.getCoordinates();
        this.car = h.getCar();
        this.id = idCounter;     /// возможно стоит переделать
        idCounter++;
        this.creationDate = LocalDateTime.now();
    }
    private final @AutoGenerated long id; //Значение поля должно быть больше 0, Значение этого поля должно быть уникальным, Значение этого поля должно генерироваться автоматически
    private final @NotNull String name; //Поле не может быть null, Строка не может быть пустой
    private final @NotNull Coordinates coordinates; //Поле не может быть null
    private final @AutoGenerated LocalDateTime creationDate;  //Поле не может быть null, Значение этого поля должно генерироваться автоматически
    private final @NotNull Boolean realHero; //Поле не может быть null
    private final Boolean hasToothpick; //Поле может быть null
    private final Float impactSpeed; //Поле может быть null
    private final @NotNull WeaponType weaponType; //Поле не может быть null
    private final @NotNull Mood mood; //Поле не может быть null
    private final Car car; //Поле может быть null
    public String getName(){return name;}
    public Coordinates getCoordinates(){
        return coordinates;
    }
    @Override
    public String toString(){
        return "HumanBeing {\n" +
                    "\tid = " + id + "\n" +
                    "\tname = " + name + "\n"+
                    "\tcoordinates = " + coordinates + "\n"+
                    "\tcreationDate = " + creationDate + "\n"+
                    "\trealHero = " + realHero + "\n"+
                    "\thasToothpick = " + hasToothpick + "\n"+
                    "\timpactSpeed = " + impactSpeed + "\n" +
                    "\tweaponType = " + weaponType + "\n"+
                    "\tmood = " + mood + "\n"+
                    "\tcar = " + car + "\n" +
                "}";

    }

    @Override
    public int compareTo(HumanBeing o) {
        return (int)(o.id - this.id);
    }//переписать
}