package StoredClasses;

import StoredClasses.annotations.AutoGenerated;
import StoredClasses.annotations.NotNull;
import StoredClasses.enums.Mood;
import StoredClasses.enums.WeaponType;
import StoredClasses.forms.HumanBeingForm;
import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

import reading.generators.Generator;
import reading.generators.HumanBeingGenerator;


import java.time.LocalDateTime;

@XStreamAlias("human")
public class HumanBeing implements Comparable<HumanBeing>, Checkable{
    /**
     * returns HumanBeing generator
     * @return Generator
     */
    public static Generator getGenerator(){
        return new HumanBeingGenerator();
    }
    @XStreamOmitField
    public static long idCounter = 1;
    @XStreamOmitField
    private final @AutoGenerated long id; //Значение поля должно быть больше 0, Значение этого поля должно быть уникальным, Значение этого поля должно генерироваться автоматически
    @XStreamOmitField
    private final @AutoGenerated LocalDateTime creationDate;  //Поле не может быть null, Значение этого поля должно генерироваться автоматически
    private @NotNull String name; //Поле не может быть null, Строка не может быть пустой
    private @NotNull Coordinates coordinates; //Поле не может быть null
    private @NotNull Boolean realHero; //Поле не может быть null
    private Boolean hasToothpick; //Поле может быть null
    private Float impactSpeed; //Поле может быть null
    private @NotNull WeaponType weaponType; //Поле не может быть null
    private @NotNull Mood mood; //Поле не может быть null
    private Car car; //Поле может быть null

    /**
     * generates HumanBeing from HumanBeingForm
     * @param h - HumanBeingForm object
     */
    public HumanBeing(HumanBeingForm h) {
        this.name = h.getName();
        this.mood = h.getMood();
        this.weaponType = h.getWeaponType();
        this.realHero = h.getRealHero();
        this.coordinates = h.getCoordinates();
        this.impactSpeed = h.getImpactSpeed();
        this.hasToothpick = h.getHasToothPick();
        this.car = h.getCar();
        if (car != null) car.check();
        if (coordinates != null) coordinates.check();

        this.id = idCounter;                                                                /// точно стоит переделать
        idCounter++;
        this.creationDate = LocalDateTime.now();
        this.check();
    }

    /**
     * @return string
     */
    public String getName() {
        return name;
    }

    /**
     * @return Coordinates
     */
    public Coordinates getCoordinates() {
        return coordinates;
    }

    /**
     * @return id
     */
    public long getId() {
        return id;
    }

    /**
     * @return impactSpeed
     */
    public Float getImpactSpeed() {
        return impactSpeed;
    }

    /**
     * @return mood
     */
    public Mood getMood() {
        return mood;
    }

    /**
     * @return realHero
     */
    public boolean isRealHero() {
        return realHero;
    }

    /**
     * @return hasToothPick
     */
    public Boolean ifHasToothpick() {
        return hasToothpick;
    }

    /**
     * @return weaponType
     */
    public WeaponType getWeaponType() {
        return weaponType;
    }

    /**
     * updates object (except id and creationDate)
     * @param obj - new HumanBeing
     */
    public void update(HumanBeing obj) {
        this.name = obj.getName();
        this.car = obj.car;
        this.coordinates = obj.getCoordinates();
        this.mood = obj.getMood();
        this.realHero = obj.isRealHero();
        this.hasToothpick = obj.ifHasToothpick();
        this.impactSpeed = obj.getImpactSpeed();
        this.weaponType = obj.getWeaponType();
    }

    @Override
    public String toString() {
        return "HumanBeing {\n" +
                "\tid = " + id + "\n" +
                "\tname = " + name + "\n" +
                "\tcoordinates = " + coordinates + "\n" +
                "\tcreationDate = " + creationDate + "\n" +
                "\trealHero = " + realHero + "\n" +
                "\thasToothpick = " + hasToothpick + "\n" +
                "\timpactSpeed = " + impactSpeed + "\n" +
                "\tweaponType = " + weaponType + "\n" +
                "\tmood = " + mood + "\n" +
                "\tcar = " + car + "\n" +
                "}";

    }

    @Override
    public int compareTo(HumanBeing o) {
        return this.name.compareTo(o.name);
    }
}